### PR TITLE
Perform full Composer dev dependency conflict detection

### LINKED ISSUE #113: Composer dev dependency prerequisites stage does not perform full conflict detection
The current prerequisites stage of the Composer dev dependency only detects explicit conflicts, ie. conflicts that are configured in the project's `composer.json`. Only during the execution stage does full conflict detection by Composer's solver occur. This can cause errors to occur during the execution stage that are not caught during the prerequisites stage. This behaviour is unexpected, but perhaps preferable to other solutions.

Solutions:

 1. Perform a regular `require --dev`, actually performing conflict detection. This also installs the dependencies, making the execution stage of the task a no-op. Make sure InstallComposerDevDependencyTaskExecutor's prerequisites stage is also rolled back on SIGKILL.
 1. ~Don't perform conflict detection in the prerequisites stage, just require the packages in the execution stage. Error reporting in the execution stage should be improved to display the error message Composer outputs to help the Developer debug the conflict situation.~
 1. ~Remove the `composer install --dry-run` that occurs after `composer require --dev --no-update` in the prerequisites stage. [This installation](https://github.com/ibuildingsnl/qa-tools/blob/21d72c944765e971edabb280dd6732c766683b94/src/Core/Composer/CliComposerProject.php#L95) does not provide any information, as it just installs the locked dependencies. Improve error reporting in the execution stage to display the error message Composer outputs to help the Developer debug the conflict situation. I prefer this solution.~

### PR DESCRIPTION
**Pull request by rjkip**
Perform full Composer dev dependency conflict detection by actually requiring the dev dependencies. The configuration is then stored in memory, only to be restored during the execution phase. As the packages are cached, this shouldn't introduce such a performance hit.

Fixes #113

### CODE REVIEW

File: src/Core/Composer/CliComposerProject.php [hunk 1]
```diff
@@ -136,24 +93,35 @@ public function requireDevDependencies(PackageSet $packages)
         }
     }
 
-    public function backUpConfiguration()
+    public function backUpConfiguration($key)
```
Comment (rjd22) [inline src/Core/Composer/CliComposerProject.php]: It's not directly obvious what this key is meant for. Is is a key to decrypt a backup configuration? Is it the key needed for the backup system to locate the configuration? `$key` can be many things.

File: tests/unit/Core/Task/Executor/InstallComposerDevDependencyTaskExecutorTest.php [hunk 2]
```diff
@@ -83,16 +83,30 @@ public function verifies_that_added_dependencies_dont_conflict_with_current_conf
...
+            ->ordered();
+        $this->composerProject
+            ->shouldReceive('restoreConfiguration')
+            ->with(InstallComposerDevDependencyTaskExecutor::CONFIGURATION_ORIGINAL)
+            ->once()
+            ->ordered();
+
+        $arePrerequisitesMet = $this->executor->arePrerequisitesMet($tasks, $this->project, $this->interviewer);
+
+        $this->assertTrue($arePrerequisitesMet, 'Nothing should prevent installation of lefty/loosy 2');
```
Comment (rpkamp) [inline tests/unit/Core/Task/Executor/InstallComposerDevDependencyTaskExecutorTest.php]: I'm not entirely sure what this test is testing. The test code does not seem to conform the test name.

File: src/Core/Composer/RuntimeException.php [hunk 3]
```diff
@@ -9,27 +9,39 @@
...
      * Returns a detailed, ideally human-readable, explanation of the cause of this exception.
      *
      * @return string
      */
-    public function getCause()
+    public function getDetailedCause()
     {
-        return $this->cause;
+        if (!$this->hasDetailedCause()) {
+            throw new RuntimeException('This RuntimeException has no detailed cause');
```
Comment (rjkip) [inline src/Core/Composer/RuntimeException.php]: How does an empty exception message help debug this exceptional situation?

Comment (rpkamp) [inline src/Core/Composer/RuntimeException.php]: It doesn't. I'm just not sure an exception should throw a new instance of itself.
I would at least suggest to add a detailed cause to the new exception to prevent the infinite loops we just prevented IRL :smile:

File: tests/unit/Core/Task/Executor/InstallComposerDevDependencyTaskExecutorTest.php (hunk 2 above)
Comment (rjkip) [inline tests/unit/Core/Task/Executor/InstallComposerDevDependencyTaskExecutorTest.php]: The test has the intention to test that dev dependencies can indeed be installed when there are no package/version conflicts. In the end it indeed asserts that the installation can be performed. Do you have a suggestion how to make this more obvious?

Comment (rpkamp) [inline tests/unit/Core/Task/Executor/InstallComposerDevDependencyTaskExecutorTest.php]: It seems to also test the behaviour of backups, so I'm getting two mixed concerns from this test. Maybe do one test with the mocks and ordered etc, and one where you don't make any assumptions on what is being called and why.

File: src/Core/Composer/CliComposerProject.php [hunk 4]
```diff
@@ -71,49 +73,33 @@ public function initialise()
...
-            ->setWorkingDirectory($this->directory)
-            ->setEnv('COMPOSER_HOME', getenv('COMPOSER_HOME'))
-            ->setTimeout(null)
-            ->getProcess();
+        $targetConfiguration = $this->readConfiguration();
 
-        if ($process->run() !== 0) {
-            // Restore the old JSON in case Composer wrote to the Composer file anyway.
-            $this->restoreConfiguration();
+        try {
```
Comment (rpkamp) [inline src/Core/Composer/CliComposerProject.php]: No catch?

File: src/Core/Composer/RequireCache.php [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+     */
+    private function getKey(Configuration $targetConfiguration, PackageSet $requiredPackages)
+    {
+        $packageDescriptors = join(',', $requiredPackages->getDescriptors());
+        $composerJson = $targetConfiguration->getComposerJson();
+        $composerLockJson = $targetConfiguration->hasLockedDependencies()
+            ? $targetConfiguration->getComposerLockJson()
+            : '';
+
+        return sha1(join(':', array_filter([$packageDescriptors, $composerJson, $composerLockJson])));
```
Comment (rpkamp) [inline src/Core/Composer/RequireCache.php]: I would not put array_filter here, because then you could get a join results `A:B` and `A:B` which look the same but are not, because actually they were `:A:B` and `A:B:`.

Slim chance of it happening, but it doesn't hurt to eliminate the option IMO.

File: tests/unit/Core/Composer/RequireCacheTest.php [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+use Ibuildings\QaTools\Core\Composer\RequireCache;
+use Ibuildings\QaTools\Core\Exception\RuntimeException;
+use PHPUnit\Framework\TestCase;
+
+class RequireCacheTest extends TestCase
+{
+    /** @test */
+    public function stores_successful_requires()
+    {
+
```
Comment (rpkamp) [inline tests/unit/Core/Composer/RequireCacheTest.php]: nitpick: no need for this blank line

File: tests/unit/Core/Composer/RequireCacheTest.php [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+        $cache = new RequireCache();
+
+        $cache->storeConfiguration($targetConfiguration, $requiredPackages, $newConfiguration);
+    }
+
+    /** @test */
+    public function stores_successful_requires_of_0_packages()
+    {
+
```
Comment (rpkamp) [inline tests/unit/Core/Composer/RequireCacheTest.php]: nitpick: no need for this blank line

File: src/Core/Composer/CliComposerProject.php [hunk 8]
```diff
@@ -41,6 +41,8 @@ public function __construct($directory, $composerBinary, LoggerInterface $logger
         $this->directory = $directory;
         $this->composerBinary = $composerBinary;
         $this->logger = $logger;
+
+        $this->successfulRequires = new RequireCache();
```
Comment (rpkamp) [inline src/Core/Composer/CliComposerProject.php]: This is a tight couling of this class with the RequireCache class. Are you sure you don't want to inject a RequireCache instance? Maybe even add an interface for it?

Comment (rjkip) [inline src/Core/Composer/CliComposerProject.php]: Don't see any significant advantages.

File: src/Core/Composer/CliComposerProject.php (hunk 4 above)
Comment (rjkip) [inline src/Core/Composer/CliComposerProject.php]: Letting the RuntimeException bubble. Works for me :)

**Comment by rjkip** [comment]
Thanks, rebasing on master and removing a commit and its reversion.
